config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show] do
    resources :lists do
      resources :tasks do 
        member do
          patch :complete
         end
      end
    end
  end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected 
  def after_sign_in_path_for(resourse)
    user_lists_path(current_user)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = current_user.lists
  end

  def show
    @user = User.find(params[:user_id])
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    list = List.new(list_params)
    list.user_id = params[:user_id]
    list.save
    redirect_to user_list_path(current_user, list.id)
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to user_list_path(current_user, list.id)
  end

  def destroy
    list = List.find(params[:id])
    list.delete
    redirect_to user_lists_path(current_user)
  end

  private

  def list_params
    params.require(:list).permit(:user_id, :list_name, :description)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.list_id = params[:list_id]
    task.save
    redirect_to user_list_task_path(current_user, @list, task.id)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update(task_params)
    redirect_to user_list_task_path(current_user, @list, task.id)
  end

  def destroy
    task = Task.find(params[:id])
    task.delete
    redirect_to user_list_path(current_user, @list.id)
  end

  def complete
    @task = Task.find(params[:id]) 
    @task.update_attribute(:completed_at, Time.now)
    redirect_to user_list_task_path(current_user, @list, @task.id)
  end

  private

  def set_list 
    @list = List.find(params[:list_id])
  end

  def task_params
    params.require(:task).permit(:user_id, :task_name, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YouseToDo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width">
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/"><%= image_tag("youse_logo.png", size: "130x30", alt: "Youse") %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse"  id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home</a>
            </li>
            <% if user_signed_in? %>
              <%= link_to "Your Lists", user_lists_path(current_user), class: "nav-link" %>
              <%= link_to 'Edit profile', edit_user_registration_path, :class => "nav-link" %>
              <%= link_to "Logout", destroy_user_session_path, :class => "nav-link", method: :delete %>
              <li class="nav-link">Welcome <%= current_user.email%></li>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => "nav-link" %>
              <%= link_to "Login", new_user_session_path, :class => "nav-link" %>
            <% end %>
          </ul>
        </div>
      </nav><br />
      <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<div class="list_task_img">
  <div class="list_task_container">
    <h2> Edit your to do list</h2>
    <%= form_for [current_user, @list] do |l| %>
    <%= l.text_field :list_name, placeholder: "Put your list name here" %>
    <%= l.text_area :description, placeholder: "Need a clue about your list? put it here!", class: "small-textarea" %><br />
    <%= l.submit 'save', data:{confirm: 'save this data?'}, class: "btn"  %>
    <%= link_to 'Back', user_list_path(current_user, @list.id), class: "btn" %>
    <% end %>
  </div>
</div> 

app/views/lists/index.html.erb
<div class="list_task_img">
  <div class="list_task_container">
    <h2>Pending Lists</h2>
    <% @lists.each do |list| %>
      <%= link_to(list.list_name, user_list_path(current_user, list.id), class: "btn1") %>
    <% end %>
    <div class="actions"><br /><br/>
      <%= link_to "New List",  new_user_list_path(current_user.id), class: "btn2" %> <br/>
    </div>
  </div>
</div>  

app/views/lists/new.html.erb
<div class="list_task_img">
  <div class="list_task_container">
    <h2> New to do list</h2>
    <%= form_for [current_user, List.new] do |l| %>
      <%= l.text_field :list_name, placeholder: "Put your list name here" %>
      <%= l.text_area :description, placeholder: "Description about your list", class: "small-textarea" %><br />
      <%= l.submit 'save', data:{confirm: 'save this data?'}, class: "btn"  %>
      <%= link_to"back", user_lists_path(current_user), class: "btn" %>
    <% end %>
  </div>
</div> 

app/views/lists/show.html.erb
<div class="list_task_img">
  <div class="list_task_container">
    <h3><%= @list.list_name %> </h3 >
    <p> Description: <%= @list.description %> </p>
    <h3>Pending Tasks</h3>
    <% @list.tasks.each do |task| %>
    <%= link_to(task.task_name, user_list_task_path(current_user, @list, task.id)) %>
    <% end %> 
    <%= link_to "Create a new task on this list", new_user_list_task_path(current_user.id, @list), class: "btn1" %> <br/>
    <div class="actions">
      <%= link_to "Edit your list data", edit_user_list_path(current_user.id), class: "btn2" %>
      <%= link_to "Erase this list", user_list_path(current_user.id), method: :delete, data:{confirm: "You want to delete this list?"}, class: "btn2" %>
    </div>
    <%= link_to "Back", user_lists_path, class:"btn" %>
  </div>
</div>  

app/views/tasks/edit.html.erb
<div class="task_img">
  <div class="list_task_container">
    <h2> Edit your task</h2>
    <%= form_for [current_user, @list, @task] do |f| %>
      <%= f.text_field :task_name, placeholder: "Put your task name here" %>
      <%= f.text_area :description, placeholder: "Description about the task", class: "small-textarea" %>     
      <%= f.submit 'save', data:{confirm: 'save this data?'}, class: "btn"  %>
      <%= link_to 'Back', user_list_task_path(current_user, @list, @task), class: "btn"  %>
    <% end %>
  </div>
</div> 

app/views/tasks/new.html.erb
<div class="task_img">
  <div class="list_task_container">
    <h2> New task </h2>
    <%= form_for [current_user, @list, Task.new] do |f| %>
    <%= f.text_field :task_name, placeholder: "Put your task name here" %>
    <%= f.text_area :description, placeholder: "Description about the task", class: "small-textarea" %>
    <%= f.submit 'save', data:{confirm: 'save this data?'}, class: "btn"  %>
    <%= link_to "back", user_list_path(current_user, @list.id), class: "btn" %>
    <% end %> 
  </div>
</div> 

app/views/tasks/show.html.erb
<div class="task_img">
  <div class="list_task_container">
    <h2><%= @task.task_name %></h2>
    <div class="actions">
    <% if @task.completed_at? %>
      <div class="task">
        <p style="opacity: 0.4;"><strike><%= @task.description %></strike></p>
      </div>
      <div class="complete">
        <%= link_to "Mark as Complete", complete_user_list_task_path(current_user.id, @list), method: :patch, class: "btn1" %>
      </div><br />
      <div class="delete">
       <%= link_to "Erase this task", user_list_task_path(current_user.id), method: :delete, data:{confirm: "You want to delete this task?"}, class: "btn2"%>
      </div><br />
    <% else %>
      <div class="task">
        <p><%= @task.description %></p>
      </div><br />
      <div class="complete">
        <%= link_to "Mark as Complete", complete_user_list_task_path(current_user.id, @list), method: :patch, class: "btn1" %>
      </div><br />
      <div class="delete">
        <%= link_to "Erase this task", user_list_task_path(current_user.id), method: :delete, data:{confirm: "You want to delete this task?"}, class: "btn2"%>
      </div><br />
    <% end %>
      <%= link_to "Edit your task data",  edit_user_list_task_path(current_user.id), class: "btn2"%>
    </div>
    <%= link_to "back", user_list_path(current_user, @list.id), class: "btn" %>
  </div>
</div> 

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<div class="welcome_img"></div>